<?php
$usuarios = array(
    array(
    "nombre"=>"ej1",
    "user"=>"ej1",
    "psw"=>"1234ej1",
    "perfil"=>"ej1"),
    array(
    "nombre"=>"ej2",
    "user"=>"ej2",
    "psw"=>"1234ej2",
    "perfil"=>"ej2"),
    array(
    "nombre"=>"admin",
    "user"=>"admin",
    "psw"=>"1234admin",
    "perfil"=>"admin")
);
?>